"""add platform_output_copies

Revision ID: 20ae46faceb1
Revises: 2add83d5011c
Create Date: 2026-05-10 15:31:50.385252

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '20ae46faceb1'
down_revision: Union[str, Sequence[str], None] = '2add83d5011c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('platform_output_copies',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('sku_id', sa.String(length=36), nullable=False),
    sa.Column('platform', sa.String(length=20), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('subtitle', sa.String(length=200), nullable=False),
    sa.Column('selling_points', sa.JSON(), nullable=False),
    sa.Column('description_md', sa.Text(), nullable=False),
    sa.Column('category_path', sa.String(length=200), nullable=False),
    sa.Column('keywords', sa.JSON(), nullable=False),
    sa.Column('hashtags', sa.JSON(), nullable=False),
    sa.Column('raw_response', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['sku_id'], ['skus.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('platform_output_copies')
    # ### end Alembic commands ###
