"""add video_script

Revision ID: f3aaa1c81f2b
Revises: 20ae46faceb1
Create Date: 2026-05-10 19:34:09.898541

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f3aaa1c81f2b'
down_revision: Union[str, Sequence[str], None] = '20ae46faceb1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('platform_output_copies', sa.Column('video_script', sa.Text(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('platform_output_copies', 'video_script')
    # ### end Alembic commands ###
