/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/projects": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Projects */
        get: operations["list_projects_api_projects_get"];
        put?: never;
        /** Create Project */
        post: operations["create_project_api_projects_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/projects/{project_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Project */
        get: operations["get_project_api_projects__project_id__get"];
        put?: never;
        post?: never;
        /** Delete Project */
        delete: operations["delete_project_api_projects__project_id__delete"];
        options?: never;
        head?: never;
        /**
         * Patch Project
         * @description 改名 / 改描述。改名会重命名磁盘目录并把所有子资源里的绝对路径前缀替换。
         */
        patch: operations["patch_project_api_projects__project_id__patch"];
        trace?: never;
    };
    "/api/projects/{project_id}/scenes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Scenes */
        get: operations["list_scenes_api_projects__project_id__scenes_get"];
        put?: never;
        /** Create Scene */
        post: operations["create_scene_api_projects__project_id__scenes_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/projects/{project_id}/scenes/{scene_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Update Scene */
        put: operations["update_scene_api_projects__project_id__scenes__scene_id__put"];
        post?: never;
        /** Delete Scene */
        delete: operations["delete_scene_api_projects__project_id__scenes__scene_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/projects/{project_id}/scenes/import-defaults": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Import Default Scenes
         * @description 导入默认模板（重名跳过）。代表图通过 ref_image_path = 'scene_covers/<file>' 注入。
         */
        post: operations["import_default_scenes_api_projects__project_id__scenes_import_defaults_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/projects/{project_id}/scenes-ai/expand-from-keywords": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Expand From Keywords */
        post: operations["expand_from_keywords_api_projects__project_id__scenes_ai_expand_from_keywords_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/projects/{project_id}/scenes-ai/batch-generate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Batch Generate
         * @description 批量生成 N 个该节庆下的模板。立即返回占位 Scene，后台并发填充。
         */
        post: operations["batch_generate_api_projects__project_id__scenes_ai_batch_generate_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/projects/{project_id}/scenes-ai/queue-from-keywords": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Queue From Keywords
         * @description Fire-and-forget 关键词模板生成。立即返回占位 Scene id，后台填充。
         */
        post: operations["queue_from_keywords_api_projects__project_id__scenes_ai_queue_from_keywords_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/projects/{project_id}/scenes-ai/expand-from-reference": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Expand From Reference */
        post: operations["expand_from_reference_api_projects__project_id__scenes_ai_expand_from_reference_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/projects/{project_id}/skus": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Skus */
        get: operations["list_skus_api_projects__project_id__skus_get"];
        put?: never;
        /** Create Sku */
        post: operations["create_sku_api_projects__project_id__skus_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/projects/{project_id}/skus/{sku_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Sku */
        get: operations["get_sku_api_projects__project_id__skus__sku_id__get"];
        put?: never;
        post?: never;
        /** Delete Sku */
        delete: operations["delete_sku_api_projects__project_id__skus__sku_id__delete"];
        options?: never;
        head?: never;
        /**
         * Patch Sku
         * @description 更新 SKU 字段：name / scene_id / clear_scene。
         */
        patch: operations["patch_sku_api_projects__project_id__skus__sku_id__patch"];
        trace?: never;
    };
    "/api/projects/{project_id}/skus/{sku_id}/dimensions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Update Dimensions
         * @description 更新 SKU 物理尺寸（cm）。三项可分别为空。改尺寸后前端可单独触发 regenerate。
         */
        patch: operations["update_dimensions_api_projects__project_id__skus__sku_id__dimensions_patch"];
        trace?: never;
    };
    "/api/projects/{project_id}/skus/{sku_id}/images": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Upload Image */
        post: operations["upload_image_api_projects__project_id__skus__sku_id__images_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/projects/{project_id}/skus/{sku_id}/images/{image_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Delete Image */
        delete: operations["delete_image_api_projects__project_id__skus__sku_id__images__image_id__delete"];
        options?: never;
        head?: never;
        /**
         * Patch Image
         * @description 改单图的 scene_id（per-image 模板覆盖）。
         */
        patch: operations["patch_image_api_projects__project_id__skus__sku_id__images__image_id__patch"];
        trace?: never;
    };
    "/api/projects/{project_id}/skus/{sku_id}/variants/{variant_id}/images/reorder": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Reorder Images
         * @description 整体重写该变体下原图的 order_index。前端拖拽完拿到完整新顺序 POST 过来。
         */
        post: operations["reorder_images_api_projects__project_id__skus__sku_id__variants__variant_id__images_reorder_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/projects/{project_id}/skus/{sku_id}/preview-prompt": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Preview Prompt
         * @description 返回该 SKU 当前 scene 拼装出的 ratio 完整 prompt（前端展示用）。
         *     - disable_scene=true → 模拟"启用模板"关闭：纯人工 prompt 模式
         *     - has_reference=true → 参考图驱动模式（scene 强制忽略；模板/参考图二选一）
         *     preview 与实际 codex 提交走同一个 build_master_prompt，保证一致。
         */
        get: operations["preview_prompt_api_projects__project_id__skus__sku_id__preview_prompt_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/projects/{project_id}/skus/{sku_id}/process": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Process Sku
         * @description 触发生成。
         *     - image_ids 指定：只处理这些图（跨 variant）
         *     - 否则按 variant_id 处理（None = 所有 variant）
         *     - ratios：未指定即全部 8 种规格
         */
        post: operations["process_sku_api_projects__project_id__skus__sku_id__process_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/projects/{project_id}/skus/{sku_id}/cancel": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Cancel Sku
         * @description 请求停止处理。Pipeline 会在下一个 master 完成后检测到并 bail；已生成的 master 保留。
         */
        post: operations["cancel_sku_api_projects__project_id__skus__sku_id__cancel_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/projects/{project_id}/skus/{sku_id}/images/{image_id}/regenerate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Regenerate Single Image
         * @description 重新生成某张原图的全部规格（默认 8 比例，可指定 ratios 子集）。
         *     跳过该图当前 in-flight 状态（避免重复入队）。
         */
        post: operations["regenerate_single_image_api_projects__project_id__skus__sku_id__images__image_id__regenerate_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/projects/{project_id}/skus/{sku_id}/master-versions/delete": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Delete Master Version
         * @description 删除某张 master 图的一个版本。如删的是 primary，下一个版本自动升 primary。
         */
        post: operations["delete_master_version_api_projects__project_id__skus__sku_id__master_versions_delete_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/projects/{project_id}/skus/{sku_id}/images/{image_id}/delete-all-masters": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Delete All Masters For Image
         * @description 删除该原图下所有 master 版本（含历史 + primary）。物理文件 + DB 一并清。
         */
        post: operations["delete_all_masters_for_image_api_projects__project_id__skus__sku_id__images__image_id__delete_all_masters_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/projects/{project_id}/skus/{sku_id}/variants/{variant_id}/detail/compose": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Compose Detail Page
         * @description 用用户选定的 image_keys 顺序重渲该变体在 3 平台的详情页。
         *
         *     第一个 image_key 作为 hero（建议 1x1）；其余按顺序作为 full_image 或 size_diagram module。
         *     标题/卖点段始终保留（来自该变体的 PlatformOutputCopy）。
         */
        post: operations["compose_detail_page_api_projects__project_id__skus__sku_id__variants__variant_id__detail_compose_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/projects/{project_id}/skus/{sku_id}/variants/{variant_id}/dimension/apply-to-detail": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Apply Dimension To Detail
         * @description 把指定 style 的尺寸图作为 module 加入该变体的详情页底部并重渲 3 平台。
         */
        post: operations["apply_dimension_to_detail_api_projects__project_id__skus__sku_id__variants__variant_id__dimension_apply_to_detail_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/projects/{project_id}/skus/{sku_id}/dimension/delete-all": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Delete All Dimension
         * @description 删除该变体（缺省 default）下所有尺寸图文件 + Redis 状态。
         */
        post: operations["delete_all_dimension_api_projects__project_id__skus__sku_id__dimension_delete_all_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/projects/{project_id}/skus/{sku_id}/dimension/delete": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Delete Dimension Image
         * @description 删除某张尺寸图（单张 = style × image_idx）。物理文件 + 状态都清。
         */
        post: operations["delete_dimension_image_api_projects__project_id__skus__sku_id__dimension_delete_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/projects/{project_id}/skus/{sku_id}/dimension/regenerate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Regenerate Dimension Diagram
         * @description 异步为指定变体（缺省 default）生成尺寸图。
         */
        post: operations["regenerate_dimension_diagram_api_projects__project_id__skus__sku_id__dimension_regenerate_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/projects/{project_id}/skus/{sku_id}/variants": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create Variant */
        post: operations["create_variant_api_projects__project_id__skus__sku_id__variants_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/projects/{project_id}/skus/{sku_id}/variants/{variant_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Delete Variant */
        delete: operations["delete_variant_api_projects__project_id__skus__sku_id__variants__variant_id__delete"];
        options?: never;
        head?: never;
        /** Update Variant */
        patch: operations["update_variant_api_projects__project_id__skus__sku_id__variants__variant_id__patch"];
        trace?: never;
    };
    "/api/projects/{project_id}/skus/{sku_id}/variants/{variant_id}/thumbnail": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Set Variant Thumbnail
         * @description Set 该变体的 SKU 色卡列表（多候选，list[0] 为主色卡）。
         *     传 image_keys=[] 或 image_key=None 清空。
         */
        post: operations["set_variant_thumbnail_api_projects__project_id__skus__sku_id__variants__variant_id__thumbnail_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/projects/{project_id}/skus/{sku_id}/download-bundle": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Download Bundle
         * @description 打包用户选定的资料：主图/ + SKU图/ + 详情图/ + 文案.txt
         */
        post: operations["download_bundle_api_projects__project_id__skus__sku_id__download_bundle_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/projects/{project_id}/skus/{sku_id}/download-bundle-all": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Download Bundle All
         * @description 打包用户当前变体的全平台资料。结构：
         *     主图/        ← 跨平台共用（cur.main）
         *     SKU图/       ← 跨平台共用（variant.sku_thumb_paths）
         *     <平台>/详情图/detail-template.jpg
         *     <平台>/文案.txt
         *     README.txt
         */
        post: operations["download_bundle_all_api_projects__project_id__skus__sku_id__download_bundle_all_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/skus/{sku_id}/download": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Download Sku Zip */
        get: operations["download_sku_zip_api_skus__sku_id__download_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/projects/{project_id}/download-all": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Download Project Zip
         * @description 打包所有 done 状态 SKU 的 outputs/，每个 SKU 一个目录。
         */
        get: operations["download_project_zip_api_projects__project_id__download_all_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/fs/reveal": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Reveal */
        post: operations["reveal_api_fs_reveal_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/projects/{project_id}/skus/{sku_id}/variants/{variant_id}/copy": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Copy */
        get: operations["list_copy_api_projects__project_id__skus__sku_id__variants__variant_id__copy_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/projects/{project_id}/skus/{sku_id}/variants/{variant_id}/copy/regenerate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Regenerate */
        post: operations["regenerate_api_projects__project_id__skus__sku_id__variants__variant_id__copy_regenerate_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/concurrency": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Concurrency */
        get: operations["get_concurrency_api_concurrency_get"];
        put?: never;
        /** Set Concurrency */
        post: operations["set_concurrency_api_concurrency_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/projects/{project_id}/uploads/reference": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Upload Reference
         * @description 存一张参考图到临时目录。返回 path / url；前端记到 genConfig。
         */
        post: operations["upload_reference_api_projects__project_id__uploads_reference_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_api_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AIPreview */
        AIPreview: {
            /** Name */
            name: string;
            /** Desc */
            desc: string;
            /** Prompt */
            prompt: string;
            /**
             * Prompt Zh
             * @default
             */
            prompt_zh: string;
            /** Negative Prompt */
            negative_prompt: string;
            /** Festival */
            festival: string;
            /** Cover Path */
            cover_path: string;
            /** Cover Url */
            cover_url: string;
            /**
             * Raw Text
             * @default
             */
            raw_text: string;
        };
        /** ApplyDimensionRequest */
        ApplyDimensionRequest: {
            /**
             * Style
             * @default white
             */
            style: string;
        };
        /** BatchGenerateRequest */
        BatchGenerateRequest: {
            /**
             * Festival
             * @default 通用
             */
            festival: string;
            /**
             * Count
             * @default 10
             */
            count: number;
        };
        /** Body_expand_from_reference_api_projects__project_id__scenes_ai_expand_from_reference_post */
        Body_expand_from_reference_api_projects__project_id__scenes_ai_expand_from_reference_post: {
            /** Reference */
            reference: string;
            /**
             * Festival
             * @default 通用
             */
            festival: string;
            /**
             * Style
             * @default 新中式
             */
            style: string;
        };
        /** Body_upload_image_api_projects__project_id__skus__sku_id__images_post */
        Body_upload_image_api_projects__project_id__skus__sku_id__images_post: {
            /** File */
            file: string;
        };
        /** Body_upload_reference_api_projects__project_id__uploads_reference_post */
        Body_upload_reference_api_projects__project_id__uploads_reference_post: {
            /** File */
            file: string;
        };
        /** BundleAllRequest */
        BundleAllRequest: {
            /** Variant Id */
            variant_id: string;
            /**
             * Main Keys
             * @default []
             */
            main_keys: string[];
            /**
             * Detail Keys
             * @default []
             */
            detail_keys: string[];
        };
        /** BundleRequest */
        BundleRequest: {
            /** Platform */
            platform: string;
            /** Variant Id */
            variant_id: string;
            /**
             * Main Keys
             * @default []
             */
            main_keys: string[];
            /**
             * Detail Keys
             * @default []
             */
            detail_keys: string[];
        };
        /** CopyOut */
        CopyOut: {
            /** Id */
            id: string;
            /** Platform */
            platform: string;
            /** Title */
            title: string;
            /** Subtitle */
            subtitle: string;
            /** Selling Points */
            selling_points: string[];
            /** Description Md */
            description_md: string;
            /** Category Path */
            category_path: string;
            /** Keywords */
            keywords: string[];
            /** Hashtags */
            hashtags: string[];
            /**
             * Video Script
             * @default
             */
            video_script: string;
            /** Detail Template Url */
            detail_template_url?: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /** DeleteMasterVersionRequest */
        DeleteMasterVersionRequest: {
            /** Image Id */
            image_id: string;
            /** Ratio */
            ratio: string;
            /** Path */
            path: string;
        };
        /** DetailComposeRequest */
        DetailComposeRequest: {
            /** Image Keys */
            image_keys: string[];
        };
        /** DimensionDeleteRequest */
        DimensionDeleteRequest: {
            /** Variant Id */
            variant_id: string;
            /** Style */
            style: string;
            /** Image Idx */
            image_idx: number;
        };
        /** DimensionRegenerateRequest */
        DimensionRegenerateRequest: {
            /**
             * Styles
             * @default [
             *       "white"
             *     ]
             */
            styles: string[];
            /** Image Indices */
            image_indices?: number[] | null;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** ImagePatchRequest */
        ImagePatchRequest: {
            /** Scene Id */
            scene_id?: string | null;
        };
        /** KeywordsExpandRequest */
        KeywordsExpandRequest: {
            /** Keywords */
            keywords: string[];
            /**
             * Festival
             * @default 通用
             */
            festival: string;
            /**
             * Style
             * @default 新中式
             */
            style: string;
        };
        /** ProcessRequest */
        ProcessRequest: {
            /** Ratios */
            ratios?: string[] | null;
            /**
             * Extra Prompt
             * @default
             */
            extra_prompt: string;
            /**
             * Extra Negative Prompt
             * @default
             */
            extra_negative_prompt: string;
            /**
             * Extra Weight
             * @default 0
             */
            extra_weight: number;
            /** Image Ids */
            image_ids?: string[] | null;
            /**
             * Overwrite
             * @default false
             */
            overwrite: boolean;
            /**
             * Disable Scene
             * @default false
             */
            disable_scene: boolean;
            /** Reference Image Path */
            reference_image_path?: string | null;
        };
        /** ProjectCreate */
        ProjectCreate: {
            /** Name */
            name: string;
            /**
             * Desc
             * @default
             */
            desc: string;
            /**
             * Copy Default Scenes
             * @default true
             */
            copy_default_scenes: boolean;
        };
        /** ProjectOut */
        ProjectOut: {
            /** Id */
            id: string;
            /** Name */
            name: string;
            /** Desc */
            desc: string;
            /** Root Path */
            root_path: string;
            /** Sku Count */
            sku_count: number;
            /** Scene Count */
            scene_count: number;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /** ProjectPatch */
        ProjectPatch: {
            /** Name */
            name?: string | null;
            /** Desc */
            desc?: string | null;
        };
        /** QueueKeywordsRequest */
        QueueKeywordsRequest: {
            /** Keywords */
            keywords: string[];
            /**
             * Festival
             * @default 通用
             */
            festival: string;
            /**
             * Style
             * @default 新中式
             */
            style: string;
        };
        /** RegenerateImageRequest */
        RegenerateImageRequest: {
            /** Ratios */
            ratios?: string[] | null;
            /**
             * Extra Prompt
             * @default
             */
            extra_prompt: string;
            /**
             * Extra Negative Prompt
             * @default
             */
            extra_negative_prompt: string;
            /**
             * Extra Weight
             * @default 0
             */
            extra_weight: number;
        };
        /** ReorderRequest */
        ReorderRequest: {
            /** Image Ids */
            image_ids: string[];
        };
        /** RevealReq */
        RevealReq: {
            /** Path */
            path: string;
        };
        /** SKUCreate */
        SKUCreate: {
            /** Name */
            name: string;
            /** Scene Id */
            scene_id?: string | null;
        };
        /** SKUDimensions */
        SKUDimensions: {
            /** Length Cm */
            length_cm?: number | null;
            /** Width Cm */
            width_cm?: number | null;
            /** Height Cm */
            height_cm?: number | null;
        };
        /** SKUOut */
        SKUOut: {
            /** Id */
            id: string;
            /** Project Id */
            project_id: string;
            /** Scene Id */
            scene_id: string | null;
            /** Name */
            name: string;
            /** Status */
            status: string;
            /** Length Cm */
            length_cm?: number | null;
            /** Width Cm */
            width_cm?: number | null;
            /** Height Cm */
            height_cm?: number | null;
            /** Variants */
            variants?: components["schemas"]["VariantOut"][];
            /** Images */
            images?: components["schemas"]["SourceImageOut"][];
            /** Dimension Urls */
            dimension_urls?: {
                [key: string]: string;
            };
            /** Dimension States */
            dimension_states?: {
                [key: string]: {
                    [key: string]: unknown;
                };
            };
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /** SceneCreate */
        SceneCreate: {
            /** Name */
            name: string;
            /**
             * Category
             * @default 自定义
             */
            category: string;
            /**
             * Desc
             * @default
             */
            desc: string;
            /** Prompt */
            prompt: string;
            /**
             * Negative Prompt
             * @default
             */
            negative_prompt: string;
            /**
             * Ip Adapter Weight
             * @default 60
             */
            ip_adapter_weight: number;
            /**
             * Base Model
             * @default flux-dev-fp8
             */
            base_model: string;
            /**
             * Festival
             * @default 通用
             */
            festival: string;
            /**
             * Created By
             * @default user
             */
            created_by: string;
            /** Cover Path */
            cover_path?: string | null;
        };
        /** SceneOut */
        SceneOut: {
            /** Id */
            id: string;
            /** Project Id */
            project_id: string;
            /** Name */
            name: string;
            /** Category */
            category: string;
            /** Desc */
            desc: string;
            /** Prompt */
            prompt: string;
            /** Negative Prompt */
            negative_prompt: string;
            /** Ip Adapter Weight */
            ip_adapter_weight: number;
            /** Base Model */
            base_model: string;
            /**
             * Festival
             * @default 通用
             */
            festival: string;
            /**
             * Created By
             * @default user
             */
            created_by: string;
            /** Cover Url */
            cover_url?: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /** SetConcurrencyRequest */
        SetConcurrencyRequest: {
            /** Count */
            count: number;
        };
        /** SkuPatchRequest */
        SkuPatchRequest: {
            /** Scene Id */
            scene_id?: string | null;
            /**
             * Clear Scene
             * @default false
             */
            clear_scene: boolean;
            /** Name */
            name?: string | null;
        };
        /** SourceImageOut */
        SourceImageOut: {
            /** Id */
            id: string;
            /** Name */
            name: string;
            /** Src Path */
            src_path: string;
            /** Status */
            status: string;
            /** Progress */
            progress: number;
            /** Err Msg */
            err_msg: string | null;
            /** Master Paths */
            master_paths: {
                [key: string]: unknown;
            };
            /** Master History */
            master_history?: {
                [key: string]: unknown;
            };
            /** Derived Paths */
            derived_paths: {
                [key: string]: unknown;
            };
            /** Scene Id */
            scene_id?: string | null;
            /** Src Url */
            src_url?: string | null;
            /** Master Urls */
            master_urls?: {
                [key: string]: unknown;
            };
            /** Master History Urls */
            master_history_urls?: {
                [key: string]: unknown;
            };
            /** Derived Urls */
            derived_urls?: {
                [key: string]: unknown;
            };
            /** Pending Ratios */
            pending_ratios?: string[];
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
        /** VariantCreate */
        VariantCreate: {
            /** Color Name */
            color_name: string;
        };
        /** VariantOut */
        VariantOut: {
            /** Id */
            id: string;
            /** Color Name */
            color_name: string;
            /** Status */
            status: string;
            /** Sku Thumb Path */
            sku_thumb_path?: string | null;
            /** Sku Thumb Url */
            sku_thumb_url?: string | null;
            /** Sku Thumb Paths */
            sku_thumb_paths?: string[];
            /** Sku Thumb Urls */
            sku_thumb_urls?: string[];
            /** Images */
            images?: components["schemas"]["SourceImageOut"][];
            /** Dimension Urls */
            dimension_urls?: {
                [key: string]: string;
            };
            /** Dimension States */
            dimension_states?: {
                [key: string]: {
                    [key: string]: unknown;
                };
            };
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /**
         * VariantThumbnail
         * @description SKU 选图来源。image_keys 是有序列表（第一个 = 主色卡）。
         *     每个 key 形如 'img<idx>:<ratio>' 或 'size_white' / 'size_template'。
         *     支持单值字段 image_key 作为兼容（=单元素列表）。
         */
        VariantThumbnail: {
            /** Image Keys */
            image_keys?: string[] | null;
            /** Image Key */
            image_key?: string | null;
        };
        /** VariantUpdate */
        VariantUpdate: {
            /** Color Name */
            color_name?: string | null;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    list_projects_api_projects_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProjectOut"][];
                };
            };
        };
    };
    create_project_api_projects_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ProjectCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProjectOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_project_api_projects__project_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProjectOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_project_api_projects__project_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    patch_project_api_projects__project_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ProjectPatch"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProjectOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_scenes_api_projects__project_id__scenes_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SceneOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_scene_api_projects__project_id__scenes_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SceneCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SceneOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_scene_api_projects__project_id__scenes__scene_id__put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: string;
                scene_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SceneCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SceneOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_scene_api_projects__project_id__scenes__scene_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: string;
                scene_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    import_default_scenes_api_projects__project_id__scenes_import_defaults_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SceneOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    expand_from_keywords_api_projects__project_id__scenes_ai_expand_from_keywords_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["KeywordsExpandRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AIPreview"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    batch_generate_api_projects__project_id__scenes_ai_batch_generate_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["BatchGenerateRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    queue_from_keywords_api_projects__project_id__scenes_ai_queue_from_keywords_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["QueueKeywordsRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    expand_from_reference_api_projects__project_id__scenes_ai_expand_from_reference_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_expand_from_reference_api_projects__project_id__scenes_ai_expand_from_reference_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AIPreview"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_skus_api_projects__project_id__skus_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SKUOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_sku_api_projects__project_id__skus_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SKUCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SKUOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_sku_api_projects__project_id__skus__sku_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: string;
                sku_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SKUOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_sku_api_projects__project_id__skus__sku_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: string;
                sku_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    patch_sku_api_projects__project_id__skus__sku_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: string;
                sku_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SkuPatchRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SKUOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_dimensions_api_projects__project_id__skus__sku_id__dimensions_patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: string;
                sku_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SKUDimensions"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SKUOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    upload_image_api_projects__project_id__skus__sku_id__images_post: {
        parameters: {
            query?: {
                variant_id?: string | null;
            };
            header?: never;
            path: {
                project_id: string;
                sku_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_upload_image_api_projects__project_id__skus__sku_id__images_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SKUOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_image_api_projects__project_id__skus__sku_id__images__image_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: string;
                sku_id: string;
                image_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    patch_image_api_projects__project_id__skus__sku_id__images__image_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: string;
                sku_id: string;
                image_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ImagePatchRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SKUOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    reorder_images_api_projects__project_id__skus__sku_id__variants__variant_id__images_reorder_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: string;
                sku_id: string;
                variant_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ReorderRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SKUOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    preview_prompt_api_projects__project_id__skus__sku_id__preview_prompt_get: {
        parameters: {
            query?: {
                extra_prompt?: string;
                extra_weight?: number;
                extra_negative_prompt?: string;
                disable_scene?: boolean;
                has_reference?: boolean;
            };
            header?: never;
            path: {
                project_id: string;
                sku_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    process_sku_api_projects__project_id__skus__sku_id__process_post: {
        parameters: {
            query?: {
                variant_id?: string | null;
            };
            header?: never;
            path: {
                project_id: string;
                sku_id: string;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["ProcessRequest"] | null;
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    cancel_sku_api_projects__project_id__skus__sku_id__cancel_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: string;
                sku_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    regenerate_single_image_api_projects__project_id__skus__sku_id__images__image_id__regenerate_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: string;
                sku_id: string;
                image_id: string;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["RegenerateImageRequest"] | null;
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_master_version_api_projects__project_id__skus__sku_id__master_versions_delete_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: string;
                sku_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DeleteMasterVersionRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_all_masters_for_image_api_projects__project_id__skus__sku_id__images__image_id__delete_all_masters_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: string;
                sku_id: string;
                image_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SKUOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    compose_detail_page_api_projects__project_id__skus__sku_id__variants__variant_id__detail_compose_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: string;
                sku_id: string;
                variant_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DetailComposeRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SKUOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    apply_dimension_to_detail_api_projects__project_id__skus__sku_id__variants__variant_id__dimension_apply_to_detail_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: string;
                sku_id: string;
                variant_id: string;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["ApplyDimensionRequest"] | null;
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SKUOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_all_dimension_api_projects__project_id__skus__sku_id__dimension_delete_all_post: {
        parameters: {
            query?: {
                variant_id?: string | null;
            };
            header?: never;
            path: {
                project_id: string;
                sku_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SKUOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_dimension_image_api_projects__project_id__skus__sku_id__dimension_delete_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: string;
                sku_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DimensionDeleteRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    regenerate_dimension_diagram_api_projects__project_id__skus__sku_id__dimension_regenerate_post: {
        parameters: {
            query?: {
                variant_id?: string | null;
            };
            header?: never;
            path: {
                project_id: string;
                sku_id: string;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["DimensionRegenerateRequest"] | null;
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SKUOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_variant_api_projects__project_id__skus__sku_id__variants_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: string;
                sku_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["VariantCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_variant_api_projects__project_id__skus__sku_id__variants__variant_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: string;
                sku_id: string;
                variant_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_variant_api_projects__project_id__skus__sku_id__variants__variant_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: string;
                sku_id: string;
                variant_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["VariantUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    set_variant_thumbnail_api_projects__project_id__skus__sku_id__variants__variant_id__thumbnail_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: string;
                sku_id: string;
                variant_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["VariantThumbnail"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    download_bundle_api_projects__project_id__skus__sku_id__download_bundle_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: string;
                sku_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["BundleRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    download_bundle_all_api_projects__project_id__skus__sku_id__download_bundle_all_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: string;
                sku_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["BundleAllRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    download_sku_zip_api_skus__sku_id__download_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                sku_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    download_project_zip_api_projects__project_id__download_all_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    reveal_api_fs_reveal_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RevealReq"];
            };
        };
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_copy_api_projects__project_id__skus__sku_id__variants__variant_id__copy_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: string;
                sku_id: string;
                variant_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CopyOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    regenerate_api_projects__project_id__skus__sku_id__variants__variant_id__copy_regenerate_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: string;
                sku_id: string;
                variant_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CopyOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_concurrency_api_concurrency_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    set_concurrency_api_concurrency_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SetConcurrencyRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    upload_reference_api_projects__project_id__uploads_reference_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_upload_reference_api_projects__project_id__uploads_reference_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    health_api_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
}
